csv_file = "NewPDP 8-25.csv"

[PD_LAUNCHES]
smartsheet_name = "New PD Launches"
smartsheet_columns = [ # columns that do not match are dropped
    "Item",
    "Description",
    "Anticipated Launch Date",
    "Launch Notes",
    "eCommerce Notes",
    "Earliest PO/WO Date",
    "Photo Notes",
    "Photograph",
    "Date Photo Completed?",
    "Design Approval Date",
    "Design Approval Status",
    "How Produced",
    "Inventory Available",
    "Date Sent to Photography",
    "Center Stones Available",
]

[HOLDS]
smartsheet_name = "ROs and Holds"
smartsheet_columns = [ # columns that do not match are dropped
    "Item",
    "Description",
    "Photograph",
    "Anticipated Launch Date",
]

[RENAME_NS_COLUMNS]
# Columns to rename from NetSuite to match expected Smartsheet column names
# Format is {{ NetSuite Column }} = {{ Smartsheet Column }}
"Name" = "Item"
"Date Photo Completed" = "Date Photo Completed?"

[DATEFIELDS]
# Some columns in Smartsheets are date fields, and inputs must be coerced into isoformatted dates,
# i.e. YYYYMMDD, befor being uploaded to Smartsheets. This is only required for columns in Smartsheets
# that have a Column Type of 'Date' set in Smartsheets. 
columns = [
    "Earliest PO/WO Date",
    "Design Approval Date",
    "Date Photo Completed?",
    "Date Sent to Photography",
]